const actionTypes = Object.freeze({
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  //user
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAIL: "FETCH_ALL_USER_FAIL",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  //cart

  FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
  FETCH_CART_FAIL: "FETCH_CART_FAIL",

  EAST_CART_SUCCESS: "EAST_CART_SUCCESS",
  EAST_CART_FAIL: "EAST_CART_FAIL",

  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAIL: "ADD_TO_CART_FAIL",

  DELETE_PRODUCT_IN_CART_SUCCESS: "DELETE_PRODUCT_IN_CART_SUCCESS",
  DELETE_PRODUCT_IN_CART_FAIL: "DELETE_PRODUCT_IN_CART_FAIL",

  INCREASE_QUANTITY_SUCCESS: " INCREASE_QUANTITY_SUCCESS",
  INCREASE_QUANTITY_FAIL: " INCREASE_QUANTITY_FAIL",

  DECREASE_QUANTITY_SUCCESS: " DECREASE_QUANTITY_SUCCESS",
  DECREASE_QUANTITY_FAIL: " DECREASE_QUANTITY_FAIL",
  //admin
  FETCH_BRAND_SUCCESS: "FETCH_BRAND_SUCCESS",
  FETCH_BRAND_FAIL: "FETCH_BRAND_FAIL",

  FETCH_STATUS_PRODUCT_SUCCESS: "FETCH_STATUS_PRODUCT_SUCCESS",
  FETCH_STATUS_PRODUCT_FAIL: "FETCH_STATUS_PRODUCT_FAIL",

  FETCH_HOT_SUCCESS: "FETCH_HOT_SUCCESS",
  FETCH_HOT_FAIL: "FETCH_HOT_FAIL",

  FETCH_PAYMENT_SUCCESS: "FETCH_PAYMENT_SUCCESS",
  FETCH_PAYMENT_FAIL: "FETCH_PAYMENT_FAIL",

  FETCH_REVENUE_SUCCESS: "FETCH_REVENUE_SUCCESS",
  FETCH_REVENUE_FAIL: "FETCH_REVENUE_FAIL",

  FETCH_MOUSE_BRAND_SUCCESS: "FETCH_MOUSE_BRAND_SUCCESS",
  FETCH_MOUSE_BRAND_FAIL: "FETCH_MOUSE_BRAND_FAIL",

  FETCH_MOUSE_CATEGORY_SUCCESS: "FETCH_MOUSE_CATEGORY_SUCCESS",
  FETCH_MOUSE_CATEGORY_FAIL: "FETCH_MOUSE_CATEGORY_FAIL",

  FETCH_PRINT_BRAND_SUCCESS: "FETCH_PRINT_BRAND_SUCCESS",
  FETCH_PRINT_BRAND_FAIL: "FETCH_PRINT_BRAND_FAIL",

  FETCH_ALL_PRODUCT_SUCCESS: "FETCH_ALL_PRODUCT_SUCCESS",
  FETCH_ALL_PRODUCT_FAIL: "FETCH_ALL_PRODUCT_FAIL",

  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",

  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAIL: "DELETE_PRODUCT_FAIL",

  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",

  FETCH_PC_SUCCESS: "FETCH_PC_SUCCESS",
  FETCH_PC_FAIL: "FETCH_PC_FAIL",

  FETCH_LAPTOP_SUCCESS: "FETCH_LAPTOP_SUCCESS",
  FETCH_LAPTOP_FAIL: "FETCH_LAPTOP_FAIL",

  FETCH_MOUSE_SUCCESS: "FETCH_MOUSE_SUCCESS",
  FETCH_MOUSE_FAIL: "FETCH_MOUSE_FAIL",

  FETCH_ITEM_SUCCESS: "FETCH_ITEM_SUCCESS",
  FETCH_ITEM_FAIL: "FETCH_ITEM_FAIL",

  FETCH_PRINTER_SUCCESS: "FETCH_PRINTER_SUCCESS",
  FETCH_PRINTER_FAIL: "FETCH_PRINTER_FAIL",

  FETCH_ORDER_SUCCESS: "FETCH_ORDER_SUCCESS",
  FETCH_ORDER_FAIL: "FETCH_ORDER_FAIL",

  FETCH_TRANSACTION_SUCCESS: "FETCH_TRANSACTION_SUCCESS",
  FETCH_TRANSACTION_FAIL: "FETCH_TRANSACTION_FAIL",

  FETCH_STATUS_SUCCESS: "FETCH_STATUS_SUCCESS",
  FETCH_STATUS_FAIL: "FETCH_STATUS_FAIL",

  EDIT_STATUS_SUCCESS: "EDIT_STATUS_SUCCESS",
  EDIT_STATUS_FAIL: "EDIT_STATUS_FAIL",

  FETCH_ALL_PRODUCT_CATEGORY_SUCCESS: "FETCH_ALL_PRODUCT_CATEGORY_SUCCESS",
  FETCH_ALL_PRODUCT_CATEGORY_FAIL: "FETCH_ALL_PRODUCT_CATEGORY_FAIL",
});
export default actionTypes;